openapi: 3.0.1
info:
  title: cpuinfo
  description: A simple service to get cpuinfo as an example of using swagger-2.0
    specification and codegen
  termsOfService: http://swagger.io/terms/
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
  version: 0.0.1
servers:
- url: http://localhost:8080/cloudmesh
paths:
  /cpu:
    get:
      tags:
      - CPU
      description: Returns cpu information of the hosting server
      operationId: cpu.get_processor_name
      responses:
        200:
          description: CPU info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CPU'
components:
  schemas:
    CPU:
      required:
      - model
      type: object
      properties:
        model:
          type: string

